server:
  servlet:
    context-path: "/api"
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wbs_financial_db
    username: dev_username
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
cron:
  companies:
    expression: 0 0 * * 0

logging:
  level:
    com.example.wbsfinancialbackend.datasources: off



datasource-keys:
  iexKey: ${iex_key}
  marketstackKey: ${marketstack_key}
  finhubKey: ${finhub_key}
  alphavantageKey: ${alphavantage_key}